# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22f661da1f320c374c770583b9b1cafc32d69241b197888343ae1332cdc54b1c87a0acb02219de74571178b387caa6d634c0ac91fa15c8af542f388b662dc81c

test:
  secret_key_base: b792a7368b3ac2c473222e954d743dcfc001743697e1adb8f89a8b594167c6efea6103116ffd30a0cf72d6f5bddc9472f6533956294956a9a0c8e56f5b55a24b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
